/*
 * File: pnlMenus.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

pnlMenusUi = Ext.extend(Ext.Panel, {
    title: 'Editor de menus',
    width: 865,
    cls: 'x-panel-mc',
    style: 'padding-top:0;',
    bodyStyle: 'padding:8px;',
    initComponent: function() {
        this.items = [
            {
                xtype: 'fieldset',
                title: 'Listado',
                height: 317,
                width: 821,
                items: [
                    {
                        xtype: 'grid',
                        store: 'stoMenus',
                        height: 279,
                        autoExpandColumn: 'colNombre',
                        style: 'border-width:1px;',
                        ref: '../gridPaginas',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'texto_menu',
                                header: 'Nombre',
                                sortable: true,
                                width: 100,
                                id: 'colNombre'
                            }
                        ],
                        bbar: {
                            xtype: 'paging',
                            store: 'stoMenus',
                            style: 'border-width:0px;'
                        }
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Edición',
                labelAlign: 'top',
                flex: 1,
                items: [
                    {
                        xtype: 'form',
                        width: 799,
                        labelAlign: 'top',
                        frame: true,
                        ref: '../frmEdicion',
                        items: [
                            {
                                xtype: 'textfield',
                                fieldLabel: 'id',
                                anchor: '100%',
                                name: 'id',
                                style: 'margin-top:5px;',
                                ref: '../../txtId'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Nombre',
                                anchor: '100%',
                                name: 'texto_menu',
                                ref: '../../txtNombre'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Label',
                                anchor: '100%',
                                height: 113,
                                name: 'contenido',
                                ref: '../../txtEditorContenido',
                                id: 'editorContenido'
                            }
                        ],
                        bbar: {
                            xtype: 'toolbar',
                            style: 'border-width:1px;',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Nuevo'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Aceptar',
                                    ref: '../../../btnGuardar'
                                },
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        }
                    }
                ]
            }
        ];
        pnlMenusUi.superclass.initComponent.call(this);
    }
});
