/*
 * File: pnlMenus.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

pnlMenusUi = Ext.extend(Ext.Panel, {
    title: 'Editor de menus',
    width: 865,
    height: 451,
    cls: 'x-panel-mc',
    style: 'padding-top:0;',
    bodyStyle: 'padding:8px;',
    layout: 'hbox',
    initComponent: function() {
        this.items = [
            {
                xtype: 'fieldset',
                title: 'Listado',
                height: 317,
                style: 'float:left;',
                width: 400,
                items: [
                    {
                        xtype: 'grid',
                        store: 'stoMenus',
                        height: 212,
                        autoExpandColumn: 'colNombre',
                        style: 'border-width:1px;',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'string',
                                header: 'Nombre',
                                sortable: true,
                                width: 100,
                                id: 'colNombre'
                            }
                        ],
                        bbar: {
                            xtype: 'paging',
                            store: 'stoMenus',
                            style: 'border-width:0px;'
                        }
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Edición',
                style: 'float:left;margin-left:30px;',
                height: 317,
                items: [
                    {
                        xtype: 'form',
                        width: 300,
                        items: [
                            {
                                xtype: 'textfield',
                                fieldLabel: 'id',
                                anchor: '100%',
                                name: 'id',
                                ref: '../../txtId'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Nombre',
                                anchor: '100%',
                                name: 'nombre',
                                ref: '../../txtNombre'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Label',
                                anchor: '100%',
                                height: 240
                            }
                        ]
                    }
                ]
            }
        ];
        pnlMenusUi.superclass.initComponent.call(this);
    }
});
